### DISCUSSION TITLE
Issues on script installation

### DISCUSSION THREAD

**Discussion by fvhemert** [MattFryer/HA-Mealie-Barcode-Scanner#3] [Q&A] [answered]
Hi Matt, great initiative, really love what you are building.

This weekend I tried to install the script following your instructions outlined on GitHub and unfortunately, I am running into some issues. Maybe you can shed some light?

1. When using the path <homeassistant\pyscript\apps\barcode_lookup> the scripts do not show up as actions in the developer tools.

2. I temporary copied your scripts to <homeassistant\pyscript\>, this will populate the actions but when running the lookup action it errors out with the following error: Failed to process the returned action response data, expected a dictionary, but got <class 'NoneType'>.

I am running:
- pyscript 1.6.1 with "allow all imports" and "access hass as a global variable". I did not install the Jupyter kernel
- HA Core 2025.1.4
- HA Supervisor 2025.02.0
- HA Operating System 14.2
- HA Frontend 20250109.2

**Comment by MattFryer** [comment]
Hi
First thing to check, did you also copy the pyscript config file under the pyscript folder? Without it and the setting in it, pyscript won't pick up anything under the apps folder. 

It's also worth restarting HA after adding the files as although pyscript is supposed to detect them it sometimes doesn't. 

Regards
Matt

**Comment by fvhemert** [comment, marked as answer]
Hi Matt, thanks for getting back to me.

Your reply triggered me to further look into the config.yaml file and I think I have found the problem.

This is what I did:

1. I added `pyscript: !include pyscript/config.yaml` to "/homeassistant/configuration.yaml"
2. After reading the documentation (https://hacs-pyscript.readthedocs.io/en/stable/reference.html)  I removed `pyscript:` from "/homeassistant/pyscript/config.yaml"

I then rebooted and found alle actions are available and the lookup works.

For completeness, the /homeassistant/pyscript/config.yaml now looks like:

```
allow_all_imports: true
apps:
  barcode_lookup: 
    cache_csv: pyscript/apps/barcode_lookup/cache.csv # Caching can be disabled by removing the path to a cache file
    off_url_base: https://world.openfoodfacts.org/api/v2/product/ # OpenFoodFacts.org API base path
    upcdb_url_base: https://api.upcdatabase.org/product/ #UPCDatabase.org API base path
    upcdb_api_key: !secret upcdb_api #UPCDatabase.org API key. Can be included from HA secrets.yaml file
```

Thanks for your quick response and pointing me in the right direction.

BR Francois

**Comment by MattFryer** [comment]
Hi Francois
Ah, I've missed adding the following in the instructions. If you add the below to the HA configuration.yaml it should work with the original pyscript config.yaml file.
```yaml
homeassistant:
    packages:
        pyscript: !include pyscript/config.yaml
```
If you do it this way you don't need to modify the config.yaml. I'll update the instructions for others.

Regards
Matt
